[package]
name = "reedsolomon"
version = "0.1.0"
authors = ["tiansheng li <2305166+0x0177b11f@users.noreply.github.com>"]
edition = "2018"

keywords= ["reed-solomon", "erasure"]

license = "MIT"

[dependencies]
smallvec = "0.6"

[dev-dependencies]
rand = "0.7"